### ISSUE TITLE
Await blocks are not properly parsed

### ISSUE THREAD

**Issue by KentoNishi** [ota-meshi/svelte-eslint-parser#120]
The await block doesn't seem like it's being parsed correctly. Some screenshots:

![image](https://user-images.githubusercontent.com/38841491/145124035-eafaeadb-bc4b-44f0-82cc-a972b4cc31bb.png)

![image](https://user-images.githubusercontent.com/38841491/145123990-211978ef-d944-4633-b91a-6b68bdceb5f9.png)

Svelte docs on await block: https://svelte.dev/tutorial/await-blocks

@ota-meshi よろしくお願いします🙇‍♂️

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I can not reproduce your problem. Can you share your repository?

https://ota-meshi.github.io/svelte-eslint-parser/playground/#eJw1jjsOwjAQBa+yMg00jmit4DNQULoxziq25E+0a0DIyt0JUdy+NyNNE65MKJRoJ/uxocKdSgqMkpBLfOP5ellNNnVctJTyT4Q8j8OiTW6qesyQX+mJ1KGHx2OBwNCOswvOVucBiUoXgOs34s1sGbGQAsLJCN12RCZktjN2fdgLN1GsP6saQtI=
https://ota-meshi.github.io/svelte-eslint-parser/playground/#eJw1jjsOwjAQRK+yMg00iWij4DNQULoxzghb8ifaNSBk5e5EUdLOm6eZplyZoAbVTvZrQ6U7lxQEHUNK/OB8vVD1yJTf6QleTDZ1nPXDY08oCLUdjv2sTW6Ds9V5AnM5BJL6i7iZdS0WHogxGaXbVukSROwLh95vR1ZRLX+7DTnc

**Comment by KentoNishi** [comment]
This is the template I'm using: https://github.com/KentoNishi/svelte-typescript-template

If it's a config error on my side, it would be amazing if you could help me identify where the problem is :)

**Comment by ota-meshi** [comment]
Thank you for sharing your repository!
It seems to be a bug when combined with typescript-eslint. I will look for the cause and fix it.

**Comment by ota-meshi** [comment]
If you want to work around this issue right away, you can change the `number` to a different name.

**Comment by KentoNishi** [comment]
no problem, thanks for looking into it! in the meantime i've resorted to just storing the result of the promise in a variable

**Comment by KentoNishi** [comment]
@ota-meshi 上手くいきました！本当にありがとうございます ♥

![image](https://user-images.githubusercontent.com/38841491/145335568-99b78201-9649-44cd-b1b4-a705d91e5aca.png)

**Comment by ota-meshi** [comment]
@KentoNishi 連絡ありがとうございます。よかったです😄
