### ISSUE TITLE
Doesn't seem to understand destructuring inside a reactive statement

### ISSUE THREAD

**Issue by tivac** [ota-meshi/svelte-eslint-parser#172]
```js
$: ({ foo } = bar);
```

is totally valid & functional in svelte reactive statements. We use it heavily for pulling single fields off of object stores to limit the amount of redrawing we do.

Here's an example of it running in the svelte REPL:

https://svelte.dev/repl/ccaace4f16ca4ea2a77616192ab99e1a?version=3.48.0

But when I run this parser with the base ESLint `no-undef` rule applied it yells at me about the destructured variables not existing.

https://ota-meshi.github.io/svelte-eslint-parser/playground/#eJyrVkrOT0lVslKyKU4uyiwosYvJU1BIzs8rLlFISixSsFWoVkjLz1ewUohRAtIxSgq11jF5IDUqVgoaELlaoCqgWk2ghI0+3JSYvGqgZK1SLQADrB+9

![image](https://user-images.githubusercontent.com/49545/175433116-cbdb1265-d6c5-421e-81bf-34f701e1bb1a.png)
![image](https://user-images.githubusercontent.com/49545/175433134-f4eb5550-f30c-4cea-a8c4-e8890f84cdfb.png)

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I will try to find the cause.
