### ISSUE TITLE
`SvelteHTMLComment` is not treated as a real "comment"

### ISSUE THREAD

**Issue by shirotech** [ota-meshi/svelte-eslint-parser#183]
When calling `context.getSourceCode().getAllComments()` the array does not include nodes that are of `SvelteHTMLComment`, I'm not sure if its a bug or it is intended?

**Comment by JounQin** [comment]
You should provide a runnable reproduction to save all of our time.

**Comment by shirotech** [comment]
Sure, since this is plugin related, how would you like it to be shown?

**Comment by JounQin** [comment]
A GitHub repo reproduction with steps is always preferred.

**Comment by shirotech** [comment]
@JounQin Do you have a template for the repro repo? Otherwise it's going to take a lot of effort to show something so simple, probably way longer than fixing the issue itself. Perhaps I can show you a fix of a PR then?

**Comment by JounQin** [comment]
> Perhaps I can show you a fix of a PR then?

A PR with fix or failed test case is also great!

**Comment by ota-meshi** [comment]
Did you have any problems with not including `SvelteHTMLComment` in `getAllComments()`?

**Comment by shirotech** [comment]
> Did you have any problems with not including `SvelteHTMLComment` in `getAllComments()`?

The problem is that `SvelteHTMLComment` does not get included. Since it is not derived from a Comment node.

**Comment by ota-meshi** [comment]
Can you share with us what you want to do with `getAllComments()`?

I intentionally didn't include `SvelteHTMLComment`s in `getAllComments()` to avoid conflicts with some eslint rules. However, there is a disadvantage that eslint directive comments cannot be used.
To solve some problems, eslint-plugin-svelte introduced a mechanism to support `eslint-disable`.
https://ota-meshi.github.io/eslint-plugin-svelte/rules/comment-directive/

**Comment by JounQin** [comment]
Out of scope, we have a similar situation in [`eslint-mdx`](https://github.com/mdx-js/eslint-mdx#mdxremark) that we can't disable [`remark-lint`](https://github.com/remarkjs/remark-lint) rules with ESLint comment directive, and thankfully `remark-lint` itself supports `<!--lint disable no-unused-definitions definition-case-->`, it seems similar to `eslint svelte/comment-directive`. 👍
