### ISSUE TITLE
@typescript-eslint/no-unsafe-call with svelte-i18n and @typescript-eslint/recommended-requiring-type-checking

### ISSUE THREAD

**Issue by binarious** [ota-meshi/svelte-eslint-parser#191]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.20.0

### What version of `eslint-plugin-svelte` are you using?

2.2.0

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  extends: [
    'plugin:svelte/recommended',
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking'
  ],
  parserOptions: {
    project: ['./tsconfig.json'],
    extraFileExtensions: ['.svelte']
  },
  overrides: [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: {
        parser: "@typescript-eslint/parser",
      },
    },
  ],
  ignorePatterns: ['node_modules', 'dist']
}
```
</details>

```svelte
<script lang="ts">
  import { _ } from 'svelte-i18n';
</script>

<main>
  <input name={$_('test')}>
</main>
```

### What did you expect to happen?

No lint issues to occur.

### What actually happened?

> Unsafe call of an `any` typed value. [@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)

for `$_('test')`. This doesn't happen with https://github.com/sveltejs/eslint-plugin-svelte3.

### Link to Minimal Reproducible Example

https://github.com/binarious/eslint-plugin-svelte-repro

**Comment by binarious** [comment]
Thanks for the work @ota-meshi! Confirmed fixed in my reproducer. I still can't get this to work in a real world project. Does this rely on special `tsconfig` settings?

**Comment by ota-meshi** [comment]
The eslint-plugin-svelte dependency may refer to an old parser. 

Can you try using the new version just released?
https://github.com/ota-meshi/eslint-plugin-svelte/releases/tag/v2.3.0

**Comment by binarious** [comment]
I've forced it with `pnpm.override`. Everything is working fine. Thank you!
