### ISSUE TITLE
False positive unused import when using stores only in reactive statements

### ISSUE THREAD

**Issue by KentoNishi** [ota-meshi/svelte-eslint-parser#88]
![image](https://user-images.githubusercontent.com/38841491/135815987-02154734-b158-4cba-853a-1cdbd2633033.png)

The `savingStatus` store is only used in this one line that starts with `$:`, and the parser incorrectly marks it as an unused import. Removing the reactive statement and converting it into a function fixes it, but it's not very elegant. I'd love it if the parser could ignore the reactive `$:` statement when determining unused imports!

![image](https://user-images.githubusercontent.com/38841491/135816430-9ca04c42-1b60-4b94-9858-676bb7003057.png)

**Comment by KentoNishi** [comment]
@ota-meshi レスポンス早くてびっくりしました！わざわざお忙しい中ありがとうございます🙇‍♂️

**Comment by ota-meshi** [comment]
バグ報告ありがとうございます。そちらもでうまく動くといいのですが😅
また何かあればissueください🙏
